development: &default
  adapter: postgresql
  database: kebab-remote-api_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432
  username: postgres
  password: kebabremoteapi

test:
  <<: *default
  database: kebab-remote-api_test
